core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views as core_views

app_name = 'core'

urlpatterns = [
    url(r'^$', core_views.IndexView.as_view(), name='index'),
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
]

docs/urls.py
from django.conf.urls import url
from tagulous.views import autocomplete
from .models import DocumentTags
from . import views as docs_views

app_name = 'docs'

urlpatterns = [
    url(r'^$', docs_views.IndexView.as_view(), name='index'),
    url(r'^create/$', docs_views.DocumentCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', docs_views.DocumentUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', docs_views.DocumentDeleteView.as_view(), name='delete'),
    url(r'^tags_autocomplete/$', autocomplete, {'tag_model': DocumentTags}, name='tags_autocomplete'),
]

jeito/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^docs/', include('docs.urls')),
    url(r'^members/', include('members.urls')),
    url(r'^tracking/', include('tracking.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docs/models.py
from tika import parser
from django.db import models
from tagulous.models import TagField, TagModel
from tracking_fields.decorators import track


class DocumentTags(TagModel):
    class TagMeta:
        autocomplete_view = 'docs:tags_autocomplete'


@track('file', 'title', 'tags')
class Document(models.Model):
    file = models.FileField(u"Fichier", max_length=200, upload_to='docs/%Y/%m/%d/')
    title = models.CharField(u"Titre", max_length=200)
    tags = TagField(DocumentTags, verbose_name=u"Mots-clés", blank=True,
                    help_text="Entrez une liste de mots-clés séparés par des virgules")
    visible = models.BooleanField(u"Visible", default=True)

    def __str__(self):
        return self.title

    def text(self):
        parsed = parser.from_file(self.file.path)
        return parsed['content']

docs/forms.py
from django import forms


class DocumentSearchForm(forms.Form):
    q = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': u"Chercher..."}))

docs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, HTML
from haystack.query import SearchQuerySet
from . import forms as docs_forms
from . import models as docs_models
from .signals import post_form_save


class IndexView(LoginRequiredMixin, ListView):
    template_name = 'docs/index.html'
    model = docs_models.Document
    limit = 50

    def get_queryset(self):
        qs = SearchQuerySet().models(docs_models.Document)
        self.form = docs_forms.DocumentSearchForm(data=self.request.GET)
        if self.form.is_valid():
            q = self.form.cleaned_data.get('q', '')
            qs = qs.filter(content=q)
        qs = qs.filter(visible=True)
        self.count = qs.count()
        qs = qs[:self.limit]
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form
        context['more'] = self.count > self.limit
        context['limit'] = self.limit
        return context


class CrispyFormViewMixin(object):
    glyphicon = 'ok-sign'
    submit_text = u"OK"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.helper = FormHelper()
        form.helper.layout = Layout(*self.fields)
        form.helper.layout.append(
            HTML(u"""<button type="submit" class=\"btn btn-success\">
                       <span class="glyphicon glyphicon-{glyphicon}"></span> {text}
                     </button>""".format(glyphicon=self.glyphicon, text=self.submit_text))
        )
        form.helper.layout.append(
            HTML(u"""<a href=\"{href}\" class=\"btn btn-default\">
                       <span class="glyphicon glyphicon-remove-sign"></span> Annuler
                     </a>""".format(href=self.success_url))
        )
        return form


class SaveSignalMixin(object):
    def form_valid(self, form):
        response = super().form_valid(form)
        post_form_save.send(sender=self.model, instance=self.object)
        return response


class DocumentCreateView(LoginRequiredMixin, SaveSignalMixin, CrispyFormViewMixin, CreateView):
    model = docs_models.Document
    fields = ('file', 'title', 'tags')
    success_url = reverse_lazy('docs:index')
    glyphicon = 'plus'
    submit_text = u"Ajouter"


class DocumentUpdateView(LoginRequiredMixin, SaveSignalMixin, CrispyFormViewMixin, UpdateView):
    model = docs_models.Document
    fields = ('file', 'title', 'tags')
    success_url = reverse_lazy('docs:index')
    submit_text = u"Modifier"


class DocumentDeleteView(LoginRequiredMixin, DeleteView):
    model = docs_models.Document
    success_url = reverse_lazy('docs:index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.visible = False
        self.object.save()
        post_form_save.send(sender=self.model, instance=self.object)
        return HttpResponseRedirect(success_url)

docs/templates/docs/document_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block breadcrumbs %}

  {{ block.super }}
  <li><a href="{% url 'docs:index' %}">Documents</a></li>
  <li class="active">Supprimer</li>

{% endblock breadcrumbs %}


{% block content %}

  <h1>Supprimer le document</h1>
  <form action="{% url 'docs:delete' object.pk %}" method="post">
    {% csrf_token %}
    <p>Êtes-vous sûr de vouloir supprimer le document « {{ object.title }} » ?</p>
    <button type="submit" class="btn btn-danger">
      <span class="glyphicon glyphicon-trash"></span>
      Supprimer
    </button>
    <a href="{% url 'docs:index' %}" class="btn btn-default">
      <span class="glyphicon glyphicon-remove-sign"></span>
      Annuler
    </a>
  </form>

{% endblock content %}

docs/templates/docs/document_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block breadcrumbs %}

  {{ block.super }}
  <li><a href="{% url 'docs:index' %}">Documents</a></li>
  <li class="active">{% if object %}Modifier{% else %}Ajouter{% endif %}</li>

{% endblock breadcrumbs %}


{% block content %}

  <h1>{% if object %}Modifier le{% else %}Ajouter un{% endif %} document</h1>
  {% crispy form %}

{% endblock content %}

docs/templates/docs/index.html
{% extends 'base.html' %}


{% block breadcrumbs %}

{{ block.super }}
<li class="active">Documents</li>

{% endblock breadcrumbs %}

{% block actions %}

<hr>

<a href="{% url 'docs:create' %}" class="btn btn-primary">
  <span class="glyphicon glyphicon-plus"></span>
  Ajouter un document
</a>

{% endblock actions %}


{% block content %}

<form method="get" id="docs-search-form">
  <div class="input-group">
    {{ form.q }}
    <span class="input-group-btn">
      <button class="btn btn-default" type="submit" title="Appliquer">
        <span class="glyphicon glyphicon-search"></span>
      </button>
      <a href="{% url 'docs:index' %}" class="btn btn-default" title="Réinitialiser">
        <span class="glyphicon glyphicon-remove"></span>
      </a>
    </span>
  </div>
</form>

<table class="table table-striped table-bordered table-hover docs">
  <thead>
    <tr>
      <th>Titre</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
      <tr>
        <td>
          <a href="{{ object.object.file.url }}">{{ object.object.title }}</a>
          {% for tag in object.object.tags.all %}
            <a href="{% url 'docs:index' %}?q={{ tag }}" class="label label-default">
              {{ tag }}
            </a>
          {% endfor %}
        </td>
        <td>
          <a href="{% url 'docs:update' object.pk %}">
            <span class="glyphicon glyphicon-pencil" title="Modifier"></span>
          </a>
          <a href="{% url 'docs:delete' object.pk %}">
            <span class="glyphicon glyphicon-trash" title="Supprimer"></span>
          </a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% if more %}
  <p>Il y a plus de {{ limit }} documents. Merci de préciser votre recherche.</p>
{% endif %}

{% endblock content %}