core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views as core_views

app_name = 'core'

urlpatterns = [
    url(r'^$', core_views.IndexView.as_view(), name='index'),
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
]

docs/urls.py
from django.conf.urls import url
from tagulous.views import autocomplete
from .models import DocumentTags
from . import views as docs_views

app_name = 'docs'

urlpatterns = [
    url(r'^$', docs_views.IndexView.as_view(), name='index'),
    url(r'^create/$', docs_views.DocumentCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', docs_views.DocumentUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', docs_views.DocumentDeleteView.as_view(), name='delete'),
    url(r'^tags_autocomplete/$', autocomplete, {'tag_model': DocumentTags}, name='tags_autocomplete'),
]

jeito/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^docs/', include('docs.urls')),
    url(r'^members/', include('members.urls')),
    url(r'^tracking/', include('tracking.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.validators import RegexValidator
from django.utils.timezone import now

from mptt.models import MPTTModel, TreeForeignKey


class PersonManager(BaseUserManager):
    def create_user(self, password=None, **kwargs):
        user = self.model(**kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, **kwargs):
        return self.create_user(is_superuser=True, **kwargs)


class Structure(MPTTModel):
    TYPE_CHOICES = (
        (1, "Cercle"),
        (2, "Clan Ainé"),
        (3, "Comité directeur"),
        (4, "Département"),
        (5, "Pôle"),
        (6, "Région"),
        (7, "Ronde"),
        (8, "Siège"),
        (9, "Sommet"),
        (10, "Structure locale d'activité"),
        (11, "Structure locale rattachée"),
        (12, "Unité Défi"),
        (13, "Unité Eclé"),
        (14, "Unité Nomade"),
    )
    SUBTYPE_CHOICES = (
        (1, "Centre et terrain"),
        (2, "Groupe local"),
        (3, "Ludotheque"),
        (4, "Service vacances"),
    )

    number = models.CharField(
        "Numéro", max_length=10, unique=True,
        validators=[
            RegexValidator('\d{10}', message="Le numéro de structure comporte 10 chiffres")
        ]
    )
    name = models.CharField("Nom", max_length=100)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
    type = models.IntegerField("Type", choices=TYPE_CHOICES)
    subtype = models.IntegerField("Sous-type", choices=SUBTYPE_CHOICES, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Structure"

    class MPTTMeta:
        order_insertion_by = ['name']


class Function(models.Model):
    SECTOR_CHOICES = (
        (1, "Groupes locaux"),
        (2, "Formation"),
        (3, "Services vacances"),
        (4, "Activités ouvertes"),
        (5, "Structures support"),
    )
    CATEGORY_CHOICES = (
        (0, "Jeune"),
        (1, "Responsable"),
        (2, "Membre associé"),
    )

    code = models.CharField("Code", max_length=5)
    season = models.IntegerField()
    name_m = models.CharField("Nom masculin", max_length=100)
    name_f = models.CharField("Nom féminin", max_length=100)
    sector = models.IntegerField("Secteur", choices=SECTOR_CHOICES, null=True, blank=True)
    category = models.IntegerField("Categorie", choices=CATEGORY_CHOICES, null=True, blank=True)

    def __str__(self):
        return self.name_m

    class Meta:
        verbose_name = "Fonction"
        unique_together = ('code', 'season')


class Rate(models.Model):
    CATEGORY_CHOICES = (
        (1, 'Enfants'),
        (2, 'Cadres'),
        (3, 'Amis'),
        (4, 'Stagiaires'),
        (5, 'Services Vacances'),
        (6, 'Découverte'),
    )

    name = models.CharField("Nom", max_length=256)
    season = models.IntegerField()
    rate = models.DecimalField("Tarif", max_digits=5, decimal_places=2, null=True, blank=True)
    rate_after_tax_ex = models.DecimalField(
        "Tarif après défiscalisation", max_digits=5, decimal_places=2,
        null=True, blank=True)
    bracket = models.CharField("Tranche", max_length=100, blank=True)
    category = models.IntegerField("Catégorie", choices=CATEGORY_CHOICES, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Tarif"
        unique_together = ('name', 'season')


class Person(PermissionsMixin, AbstractBaseUser):
    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_CHOICES = (
        (GENDER_MALE, "Masculin"),
        (GENDER_FEMALE, "Féminin"),
    )

    number = models.CharField(
        u'Numéro', max_length=6, unique=True,
        validators=[
            RegexValidator('\d{6}', message="Le numéro d'adhérent comporte 6 chiffres")
        ]
    )
    first_name = models.CharField(u'Prénom', max_length=100, blank=True)
    last_name = models.CharField(u'Nom', max_length=100, blank=True)
    email = models.EmailField(u'Email', blank=True)
    gender = models.IntegerField("Genre", blank=True, null=True, choices=GENDER_CHOICES)

    USERNAME_FIELD = 'number'
    objects = PersonManager()

    class Meta:
        verbose_name = "Personne"

    def get_short_name(self):
        return u'{first_name}'.format(**self.__dict__)

    def get_full_name(self):
        return u'{first_name} {last_name}'.format(**self.__dict__)

    @property
    def is_staff(self):
        return self.is_superuser

    @property
    def is_active(self):
        if self.is_superuser:
            return True
        today = now()
        if today.month < 9:
            seasons = [today.year]
        elif today.mont == 9:
            seasons = [today.year, today.year + 1]
        else:
            seasons = [today.year + 1]
        return self.adhesions.filter(season__in=seasons).exists()


class Adhesion(models.Model):
    person = models.ForeignKey(Person, related_name='adhesions')
    season = models.IntegerField("Saison")
    date = models.DateField()
    rate = models.ForeignKey(Rate, verbose_name="Tarif")
    structure = models.ForeignKey(Structure, verbose_name="Structure", related_name='adherents')
    function = models.ForeignKey(Function, verbose_name="Fonction")

core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'core/index.html'

core/templates/core/index.html
{% extends 'base.html' %}

{% block content %}

<p>Bonjour {{ request.user.first_name.title }} ! Tu trouveras sur ce site :</p>

<a href="{% url 'docs:index' %}" class="btn btn-primary">
  <span class="glyphicon glyphicon-file"></span>
  Une base documentaire
</a>

{% endblock content %}

core/templates/core/login.html
{% extends "base.html" %}

{% block breadcrumbs %}
  {{ block.super }}
  <li class="active">Connexion</li>
{% endblock breadcrumbs %}

{% block content %}

<h1>Connexion</h1>

<div class="alert alert-warning">
  Tu trouveras ton numéro d'adhérent sur ta carte d'adhésion.
  Le mot de passe est identique à celui du portail <a href="http://entrecles.eedf.fr">Entréclés</a>.
  Il t'a été communiqué dans le courrier qui accompagne ta carte d'adhésion.
  Si la personne qui a saisi ton adhésion sur le portail a bien renseigné ton adresse, tu peux également le
  <a href="http://entrecles.eedf.fr/securite/OubliMotDePasse.aspx">recevoir par email</a>.
</div>

{% if form.errors %}
  <div class="alert alert-danger" role="alert">Le numéro d'adhérent ou le mot de passe sont incorrects. Merci de réessayer.</div>
{% endif %}

<form method="post" action="{% url 'core:login' %}">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ next }}" />
  <div class="form-group">
    <label for="id_username">Numéro d'adhérent</label>
    <input type="text" class="form-control" name="username" id="id_number">
  </div>
  <div class="form-group">
    <label for="id_numero">Mot de passe</label>
    <input type="password" class="form-control" name="password" id="id_password">
  </div>
  <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Connexion</button>
  <a href="http://entrecles.eedf.fr/securite/OubliMotDePasse.aspx" class="btn btn-default">Mot de passe perdu ?</a>
</form>



{% endblock %}