core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views as core_views

app_name = 'core'

urlpatterns = [
    url(r'^$', core_views.IndexView.as_view(), name='index'),
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
]

jeito/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^docs/', include('docs.urls')),
    url(r'^members/', include('members.urls')),
    url(r'^tracking/', include('tracking.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jeito/templates/base.html
<!DOCTYPE html>
<html lang="fr">

{% load staticfiles %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block css %}
    <link href="{% static 'core/bootstrap3/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'tagulous/lib/select2-3/select2.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/select2-bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'core/style.css' %}" rel="stylesheet" type="text/css" media="all">
  {% endblock css %}
  <title>EEDF - Jeito</title>
</head>

<body>

  <div class="container">
    <div class="row">
      <div class="col-sm-3 col-lg-2">
        <div class="main-logo"></div>
        {% if request.user.is_authenticated %}
          <hr>
          <div class="center-block">
            <span class="glyphicon glyphicon-user"></span>
            {{ request.user.first_name.title }}
            ({{ request.user.number }})
          </div>
          <div class="center-block">
            <a href="{% url 'core:logout' %}">
              <span class="glyphicon glyphicon-lock"></span>
              Déconnexion
            </a>
          </div>
        {% endif %}
        {% block actions %}
        {% endblock actions %}
      </div>
      <div class="col-sm-9 col-lg-10">
        <ol class="breadcrumb">
          {% block breadcrumbs %}
            <li><a href="{% url 'core:index' %}"><span class="glyphicon glyphicon-home"></span> Accueil</a></li>
          {% endblock breadcrumbs %}
        </ol>
        {% block content %}{% endblock content %}
      </div>
    </div>
  </div>

  <footer>
    <div class="bandeau">
      <div class="logo"></div>
      <span class="licence">
        &copy; 2016 <a href="http://www.eedf.fr">EEDF</a>
        sous <a href="https://fr.wikipedia.org/wiki/Licence_MIT">licence <strong>libre</strong> MIT</a>
      </span>
      <span class="django">
        <a href="https://www.djangoproject.com">
          Propulsé par
          <img src="{% static 'core/img/django-logo-negative.png' %}">
        </a>
      </span>
      <span class="github">
        <a href="https://www.github.com/eedf/jeito/">
          Améliore moi sur
          <img src="{% static 'core/img/github-logo.png' %}" class="baseline">
        </a>
      </span>
    </div>
  </footer>

  {% block js %}
    <script src="{% static 'core/js/jquery-1.12.0.min.js' %}"></script>
    <script src="{% static 'core/bootstrap3/js/bootstrap.js' %}"></script>
    <script src="{% static 'tagulous/lib/select2-3/select2.min.js' %}"></script>
    <script src="{% static 'tagulous/tagulous.js' %}"></script>
    <script src="{% static 'tagulous/adaptor/select2-3.js' %}"></script>
  {% endblock js %}

</body>
</html>