core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views as core_views

app_name = 'core'

urlpatterns = [
    url(r'^$', core_views.IndexView.as_view(), name='index'),
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
]

jeito/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^docs/', include('docs.urls')),
    url(r'^members/', include('members.urls')),
    url(r'^tracking/', include('tracking.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.conf.urls import url
from . import views


app_name = 'members'

urlpatterns = [
    url(r'^adhesions/$', views.AdhesionsView.as_view(), name='adhesions'),
    url(r'^adhesions/data/$', views.AdhesionsJsonView.as_view(), name='adhesions_data'),
    url(r'^tranches/$', views.TranchesView.as_view(), name='tranches'),
    url(r'^tranches/data/$', views.TranchesJsonView.as_view(), name='tranches_data'),
    url(r'^tableau/regions/$', views.TableauRegionsView.as_view(), name='tableau_regions'),
    url(r'^tableau/functions/$', views.TableauFunctionsView.as_view(), name='tableau_functions'),
]

members/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.validators import RegexValidator
from django.utils.timezone import now

from mptt.models import MPTTModel, TreeForeignKey


class PersonManager(BaseUserManager):
    def create_user(self, password=None, **kwargs):
        user = self.model(**kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, **kwargs):
        return self.create_user(is_superuser=True, **kwargs)


class Structure(MPTTModel):
    TYPE_CHOICES = (
        (1, "Cercle"),
        (2, "Clan Ainé"),
        (3, "Comité directeur"),
        (4, "Département"),
        (5, "Pôle"),
        (6, "Région"),
        (7, "Ronde"),
        (8, "Siège"),
        (9, "Sommet"),
        (10, "Structure locale d'activité"),
        (11, "Structure locale rattachée"),
        (12, "Unité Défi"),
        (13, "Unité Eclé"),
        (14, "Unité Nomade"),
    )
    SUBTYPE_CHOICES = (
        (1, "Centre et terrain"),
        (2, "Groupe local"),
        (3, "Ludotheque"),
        (4, "Service vacances"),
    )

    number = models.CharField(
        "Numéro", max_length=10, unique=True,
        validators=[
            RegexValidator('\d{10}', message="Le numéro de structure comporte 10 chiffres")
        ]
    )
    name = models.CharField("Nom", max_length=100)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
    type = models.IntegerField("Type", choices=TYPE_CHOICES)
    subtype = models.IntegerField("Sous-type", choices=SUBTYPE_CHOICES, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Structure"

    class MPTTMeta:
        order_insertion_by = ['name']


class Function(models.Model):
    SECTOR_CHOICES = (
        (1, "Groupes locaux"),
        (2, "Formation"),
        (3, "Services vacances"),
        (4, "Activités ouvertes"),
        (5, "Structures support"),
    )
    CATEGORY_CHOICES = (
        (0, "Jeune"),
        (1, "Responsable"),
        (2, "Membre associé"),
    )

    code = models.CharField("Code", max_length=5)
    season = models.IntegerField()
    name_m = models.CharField("Nom masculin", max_length=100)
    name_f = models.CharField("Nom féminin", max_length=100)
    sector = models.IntegerField("Secteur", choices=SECTOR_CHOICES, null=True, blank=True)
    category = models.IntegerField("Categorie", choices=CATEGORY_CHOICES, null=True, blank=True)

    def __str__(self):
        return self.name_m

    class Meta:
        verbose_name = "Fonction"
        unique_together = ('code', 'season')


class Rate(models.Model):
    CATEGORY_CHOICES = (
        (1, 'Enfants'),
        (2, 'Cadres'),
        (3, 'Amis'),
        (4, 'Stagiaires'),
        (5, 'Services Vacances'),
        (6, 'Découverte'),
    )

    name = models.CharField("Nom", max_length=256)
    season = models.IntegerField()
    rate = models.DecimalField("Tarif", max_digits=5, decimal_places=2, null=True, blank=True)
    rate_after_tax_ex = models.DecimalField(
        "Tarif après défiscalisation", max_digits=5, decimal_places=2,
        null=True, blank=True)
    bracket = models.CharField("Tranche", max_length=100, blank=True)
    category = models.IntegerField("Catégorie", choices=CATEGORY_CHOICES, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Tarif"
        unique_together = ('name', 'season')


class Person(PermissionsMixin, AbstractBaseUser):
    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_CHOICES = (
        (GENDER_MALE, "Masculin"),
        (GENDER_FEMALE, "Féminin"),
    )

    number = models.CharField(
        u'Numéro', max_length=6, unique=True,
        validators=[
            RegexValidator('\d{6}', message="Le numéro d'adhérent comporte 6 chiffres")
        ]
    )
    first_name = models.CharField(u'Prénom', max_length=100, blank=True)
    last_name = models.CharField(u'Nom', max_length=100, blank=True)
    email = models.EmailField(u'Email', blank=True)
    gender = models.IntegerField("Genre", blank=True, null=True, choices=GENDER_CHOICES)

    USERNAME_FIELD = 'number'
    objects = PersonManager()

    class Meta:
        verbose_name = "Personne"

    def get_short_name(self):
        return u'{first_name}'.format(**self.__dict__)

    def get_full_name(self):
        return u'{first_name} {last_name}'.format(**self.__dict__)

    @property
    def is_staff(self):
        return self.is_superuser

    @property
    def is_active(self):
        if self.is_superuser:
            return True
        today = now()
        if today.month < 9:
            seasons = [today.year]
        elif today.mont == 9:
            seasons = [today.year, today.year + 1]
        else:
            seasons = [today.year + 1]
        return self.adhesions.filter(season__in=seasons).exists()


class Adhesion(models.Model):
    person = models.ForeignKey(Person, related_name='adhesions')
    season = models.IntegerField("Saison")
    date = models.DateField()
    rate = models.ForeignKey(Rate, verbose_name="Tarif")
    structure = models.ForeignKey(Structure, verbose_name="Structure", related_name='adherents')
    function = models.ForeignKey(Function, verbose_name="Fonction")

members/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, HTML
from .utils import first_season, current_season


class AdhesionsForm(forms.Form):
    season_choices = [
        (i, "{}/{}".format(i - 1, i))
        for i in range(current_season(), first_season() - 1, -1)
    ]
    season = forms.ChoiceField(label="Saison", choices=season_choices)
    reference = forms.ChoiceField(label="Référence", choices=[(None, "Année N-1")] + season_choices)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-inline'
        self.helper.field_template = 'bootstrap3/layout/inline_field_with_label.html'
        self.helper.form_method = 'get'
        self.helper.layout = Layout(
            'season',
            'reference',
            HTML("""<button type="submit" class=\"btn btn-success\">
                    <span class="glyphicon glyphicon-ok-sign"></span> Appliquer
                    </button>"""),
        )

members/views.py
from collections import OrderedDict
from datetime import date
from django.db import connection
from django.db.models import Count
from django.http import JsonResponse
from django.utils.formats import date_format
from django.utils.timezone import now
from django.views.generic import View, TemplateView
from .forms import AdhesionsForm
from .models import Adhesion, Structure
from .utils import current_season


class AdhesionsJsonView(View):
    def serie(self, season):
        self.today = now().date()
        start = date(season - 1, 9, 1)
        end = min(date(season, 8, 31), self.today)
        sql = '''
            SELECT date, SUM(COUNT(members_structure.id)) OVER (ORDER BY date)
            FROM generate_series(%s::date, %s::date, '1 day'::interval) AS date
            LEFT JOIN members_adhesion USING (date)
            LEFT JOIN members_structure ON (members_structure.id = structure_id AND (subtype != 4 OR subtype IS NULL))
            GROUP BY date
            ORDER BY date'''
        params = [start, end]
        cursor = connection.cursor()
        cursor.execute(sql, params)
        return cursor.fetchall()

    def get(self, request):
        season = int(self.request.GET['season'])
        reference = int(self.request.GET.get('reference', '0')) or season - 1
        result = self.serie(int(season))
        ref_result = self.serie(int(reference))
        cmp_idx = min(len(result), len(ref_result)) - 1
        date1 = ref_result[cmp_idx][0].strftime('%d/%m/%Y')
        date2 = result[-1][0].strftime('%d/%m/%Y')
        nb1 = ref_result[cmp_idx][1]
        nb2 = result[-1][1]
        diff = nb2 - nb1
        if nb1:
            percent = 100 * diff / nb1
            comment = """Au <strong>{}</strong> : <strong>{}</strong> adhérents<br>
                         Au <strong>{}</strong> : <strong>{}</strong> adhérents,
                         c'est-à-dire <strong>{:+f}</strong> adhérents
                         (<strong>{:+0.1f} %</strong>)
                      """.format(date1, nb1, date2, nb2, diff, percent)
        else:
            comment = """Au <strong>{}</strong> : <strong>{}</strong> adhérents
                      """.format(date2, nb2)
        data = {
            'labels': [date_format(x[0], 'b') if x[0].day == 1 else '' for x in ref_result],
            'series': [
                [x[1] for x in ref_result],
                [x[1] for x in result],
            ],
            'comment': comment,
        }
        return JsonResponse(data)


class AdhesionsView(TemplateView):
    template_name = 'members/adhesions.html'

    def get_context_data(self, **kwargs):
        season = self.request.GET.get('season', current_season())
        reference = self.request.GET.get('reference')
        initial = self.request.GET.dict()
        initial.update({
            'season': season,
            'reference': reference,
        })
        form = AdhesionsForm(initial=initial)
        context = super().get_context_data(**kwargs)
        context['form'] = form
        context.update(initial)
        return context


class TranchesJsonView(View):

    def get(self, request):
        qs = Adhesion.objects.filter(season=2016).exclude(rate__bracket="")
        qs1 = qs.order_by('rate__bracket')
        qs1 = qs1.values('rate__bracket')
        qs1 = qs1.annotate(n=Count('id'))
        qs2 = qs.values('rate__name', 'rate__rate', 'rate__rate_after_tax_ex')
        qs2 = qs2.annotate(n=Count('id'))
        total1 = sum(x['n'] for x in qs1)
        total2 = sum(x['n'] for x in qs2)
        assert total1 == total2
        if qs.filter(rate__rate=None).exists():
            comment = "Données manquantes pour calculer la cotisation moyenne"
        else:
            average_price = sum([x['n'] * x['rate__rate'] for x in qs2]) / total2
            comment = "Cotisation moyenne : <strong>{:0.02f} €</strong>".format(float(average_price))
        if qs.filter(rate__rate_after_tax_ex=None).exists():
            comment += " (données manquantes pour calculer la cotisation moyenne après défiscalisation)"
        else:
            average_price_after_tax_ex = sum([x['n'] * x['rate__rate_after_tax_ex'] for x in qs2]) / total2
            comment += " ({:0.02f} € après défiscalisation)".format(float(average_price_after_tax_ex))
        data = {
            'labels': [x['rate__bracket'] + ' (%0.0f %%)' % (100 * x['n'] / total1) for x in qs1],
            'series': [x['n'] for x in qs1],
            'comment': comment,
        }
        return JsonResponse(data)


class TranchesView(TemplateView):
    template_name = 'members/tranches.html'


class TableauRegionsView(TemplateView):
    template_name = 'members/tableau_regions.html'

    def set_data(self, season, end):
        for region in self.regions:
            structures = region.get_descendants(include_self=True)
            adhesions = Adhesion.objects.filter(structure__in=structures, season=season, date__lte=end)
            adhesions = adhesions.exclude(structure__subtype=4)
            count = adhesions.count()
            self.data.setdefault(region.name, OrderedDict())[season] = count
        total_regions = sum([self.data[region.name][season] for region in self.regions])
        self.data.setdefault('<b>REGIONS</b>', OrderedDict())[season] = total_regions
        structures = Structure.objects.filter(number__in=('0000100000', '0000200000'))
        structures = structures.get_descendants(include_self=True)
        count = Adhesion.objects.filter(structure__in=structures, season=season, date__lte=end).count()
        self.data.setdefault('<b>SIEGE NATIONAL</b>', OrderedDict())[season] = count
        services = Structure.objects.filter(subtype=4).order_by('name')
        for service in services:
            adhesions = Adhesion.objects.filter(structure=service, season=season, date__lte=end)
            count = adhesions.count()
            self.data.setdefault(service.name, OrderedDict())[season] = count
        count = Adhesion.objects.filter(structure__subtype=4, season=season, date__lte=end).count()
        self.data.setdefault('<b>SERVICES VACANCES</b>', OrderedDict())[season] = count
        total = Adhesion.objects.filter(season=season, date__lte=end).count()
        self.data.setdefault('<b>TOTAL</b>', OrderedDict())[season] = total
        count = self.data['<b>REGIONS</b>'][season]
        count += self.data['<b>SIEGE NATIONAL</b>'][season]
        count += self.data['<b>SERVICES VACANCES</b>'][season]
        assert count == total

    def get_context_data(self, **kwargs):
        season = int(self.request.GET.get('season', current_season()))
        reference = int(self.request.GET.get('reference', '0')) or season - 1
        end = min(date(season, 8, 31), now().date())
        self.regions = Structure.objects.filter(type=6).order_by('name')
        self.data = OrderedDict()
        self.set_data(reference, end.replace(year=reference))
        self.set_data(season, end)
        for key, val in self.data.items():
            diff = val[season] - val[reference]
            if diff > 0:
                val['diff'] = "+ {}".format(diff)
            elif diff == 0:
                val['diff'] = "="
            else:
                val['diff'] = "- {}".format(-diff)
            if diff == 0:
                val['percent'] = "="
            elif not val[reference]:
                val['percent'] = "∞"
            elif diff > 0:
                val['percent'] = "+ {:0.1f} %".format(100 * diff / val[reference])
            else:
                val['percent'] = "- {:0.1f} %".format(-100 * diff / val[reference])
        context = {
            'seasons': [
                "{}/{}".format(reference - 1, reference),
                "{}/{}".format(season - 1, season),
                "Variation",
                "Variation %",
            ],
            'data': self.data,
        }
        return context


class TableauFunctionsView(TemplateView):
    template_name = 'members/tableau_functions.html'

    def set_data(self, season, end):
        all_adhesions = Adhesion.objects.filter(season=season)
        all_adhesions = all_adhesions.filter(date__lte=end)
        all_adhesions = all_adhesions.exclude(structure__subtype=4)
        for function in self.functions:
            count_func = all_adhesions.filter(function__name_m=function).count()
            self.data.setdefault(function, OrderedDict())[season] = count_func
        count_all = all_adhesions.count()
        count_others = count_all - sum([self.data[function][season] for function in self.functions])
        self.data.setdefault('Autre', OrderedDict())[season] = count_others
        self.data.setdefault('<b>TOTAL</b>', OrderedDict())[season] = count_all

    def get_context_data(self, **kwargs):
        season = self.request.GET.get('season', current_season())
        self.functions = (
            "Stagiaire",
            "Lutin",
            "Louveteau",
            "Eclaireur",
            "Ainé",
            "Participant activité",
            "Ami",
            "Parent",
            "Nomade",
            "Service civique",
        )
        season = int(self.request.GET.get('season', current_season()))
        reference = int(self.request.GET.get('reference', '0')) or season - 1
        end = min(date(season, 8, 31), now().date())
        self.data = OrderedDict()
        self.set_data(reference, end.replace(year=reference))
        self.set_data(season, end)
        for key, val in self.data.items():
            diff = val[season] - val[reference]
            if diff > 0:
                val['diff'] = "+ {}".format(diff)
            elif diff == 0:
                val['diff'] = "="
            else:
                val['diff'] = "- {}".format(-diff)
            if diff == 0:
                val['percent'] = "="
            elif not val[reference]:
                val['percent'] = "∞"
            elif diff > 0:
                val['percent'] = "+ {:0.1f} %".format(100 * diff / val[reference])

members/templates/members/adhesions.html
{% extends 'base.html' %}
{% load staticfiles crispy_forms_tags %}


{% block breadcrumbs %}

{{ block.super }}
<li class="active">Adhesions</li>

{% endblock breadcrumbs %}


{% block content %}

<h1>Cumul des membres actifs hors SV</h1>

<div class="alert alert-danger" role="alert">
  ATTENTION !!! Ces chiffres sont publiés sous réserve de validité des informations exportées par le portail
  <a href="http://entrecles.eedf.fr">Entréclés</a>
</div>

{% crispy form %}

<div class="ct-chart ct-minor-seventh"></div>

<p id="comment"></p>

{% endblock content %}


{% block css %}

{{ block.super }}
<link href="{% static 'core/chartist/chartist.min.css' %}" rel="stylesheet">
<style>
.ct-label {
  font-size: 100%;
}
.ct-series-a .ct-line {
  stroke: red;
  stroke-width: 2px;
  stroke-dasharray: 2px 2px;
}
.ct-series-b .ct-line {
  stroke: red;
  stroke-width: 2px;
}
</style>

{% endblock css %}


{% block js %}

{{ block.super }}
<script src="{% static 'core/chartist/chartist.min.js' %}"></script>
<script>
  var options = {
    showPoint: false,
    lineSmooth: false,
    axisX: {
      showGrid: false
    },
    axisY: {
    }
  };
  $.getJSON("{% url 'members:adhesions_data' %}?season={{ season }}{% if reference %}&reference={{ reference }}{% endif %}", function(data) {
    new Chartist.Line('.ct-chart', data, options);
    $('#comment').html(data['comment']);
  });
</script>

{% endblock js %}

members/templates/members/tableau_functions.html
{% extends 'base.html' %}
{% load staticfiles crispy_forms_tags %}


{% block breadcrumbs %}

{{ block.super }}
<li class="active">Tableau par fonction (hors SV)</li>

{% endblock breadcrumbs %}


{% block content %}

<h1>Tableau par fonction</h1>

<div class="alert alert-danger" role="alert">
  ATTENTION !!! Ces chiffres sont publiés sous réserve de validité des informations exportées par le portail
  <a href="http://entrecles.eedf.fr">Entréclés</a>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
        <th>Structure</th>
        {% for season in seasons %}
            <td align="right">{{  season }}</td>
        {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for function, counts in data.items %}
        <tr>
            <td>{{ function|safe }}</td>
            {% for count in counts.values %}
                <td align="right">{{ count }}</td>
            {% endfor %}
        </tr>
    {%  endfor %}
  </tbody>
</table>

{% endblock content %}

members/templates/members/tableau_regions.html
{% extends 'base.html' %}
{% load staticfiles crispy_forms_tags %}


{% block breadcrumbs %}

{{ block.super }}
<li class="active">Tableau par région</li>

{% endblock breadcrumbs %}


{% block content %}

<h1>Tableau par région</h1>

<div class="alert alert-danger" role="alert">
  ATTENTION !!! Ces chiffres sont publiés sous réserve de validité des informations exportées par le portail
  <a href="http://entrecles.eedf.fr">Entréclés</a>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
        <th>Structure</th>
        {% for season in seasons %}
            <td align="right">{{  season }}</td>
        {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for structure, counts in data.items %}
        <tr>
            <td>{{ structure|safe }}</td>
            {% for count in counts.values %}
                <td align="right">{{ count }}</td>
            {% endfor %}
        </tr>
    {%  endfor %}
  </tbody>
</table>

{% endblock content %}

members/templates/members/tranches.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block breadcrumbs %}

{{ block.super }}
<li class="active">Tranches</li>

{% endblock breadcrumbs %}


{% block content %}

<h1>Tranches de cotisation (enfants groupes locaux)</h1>

<div class="alert alert-danger" role="alert">
  ATTENTION !!! Ces chiffres sont publiés sous réserve de validité des informations exportées par le portail
  <a href="http://entrecles.eedf.fr">Entréclés</a>
</div>

<div class="ct-chart ct-minor-seventh"></div>

<p id="comment"></p>

{% endblock content %}


{% block css %}

{{ block.super }}
<link href="{% static 'core/chartist/chartist.min.css' %}" rel="stylesheet">
<style>
.ct-label {
  font-size: 100%;
  font-weight: bold;
  fill: white;
}
</style>

{% endblock css %}


{% block js %}

{{ block.super }}
<script src="{% static 'core/chartist/chartist.min.js' %}"></script>
<script>
  var options = {
  };
  $.getJSON("{% url 'members:tranches_data' %}", function(data) {
    new Chartist.Pie('.ct-chart', data, options);
    $('#comment').html(data['comment']);
  });
</script>

{% endblock js %}